### ISSUE TITLE
Save and load trained networks?

### ISSUE THREAD

**Issue by pjsgsy** [ivankarez/NeuralNetworks#31]
Hi - This library looks great. The first I have come across with GRU and appears usable! No functionality I can see to Save and load a network once trained, though. Any suggestions how this might be done? Any plans to add some functions for this?  Thanks.

**Comment by ivankarez** [comment]
Hi, thank you. You can use the `GetParametersFlat()` method of the model to get the learned parameters as a float[]. Then you can store that float array in any way. I usually use [BinaryFormatter](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter.serialize?view=net-8.0) to serialize it to a file stream. You can read that file back and load the float array to a model with `SetParametersFlat()`.

There is no way yet to store the "architecture" of the network, but if you want to save and load the weights of the network, the above method should work.
